using DevHub.Domain.Projects;
using DevHub.Domain.Users;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DevHub.Infrastructure.Persistence.Configurations;

/// <summary>Maps <see cref="ProjectMember"/> to <c>project_members</c>.</summary>
internal sealed class ProjectMemberConfiguration : IEntityTypeConfiguration<ProjectMember>
{
    public void Configure(EntityTypeBuilder<ProjectMember> builder)
    {
        // Named explicitly: members have no DbSet (they are reached only through Project), so EF
        // would otherwise name the table after the CLR type — the singular project_member.
        builder.ToTable("project_members", table => table.HasCheckConstraint(
            "ck_project_members_role",
            "role IN ('Member')"));

        builder.HasKey(member => member.Id);

        // Never generated by the database — see WorkspaceMemberConfiguration for why that
        // matters to how EF classifies the insert.
        builder.Property(member => member.Id)
            .ValueGeneratedNever();

        // Text, not an int: see ProjectRole. Keep the CHECK above in step with the enum.
        builder.Property(member => member.Role)
            .HasConversion<string>()
            .IsRequired();

        builder.Property(member => member.AddedAt).IsRequired();

        // The second line of defence behind Project.AddMember — it also covers two requests
        // adding the same user concurrently, which no in-memory check can see.
        builder.HasIndex(member => new { member.ProjectId, member.UserId })
            .IsUnique();

        builder.HasIndex(member => member.UserId);

        builder.HasOne<User>()
            .WithMany()
            .HasForeignKey(member => member.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
