using DevHub.Domain.Users;
using DevHub.Domain.Workspaces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DevHub.Infrastructure.Persistence.Configurations;

/// <summary>Maps <see cref="WorkspaceMember"/> to <c>workspace_members</c>.</summary>
internal sealed class WorkspaceMemberConfiguration : IEntityTypeConfiguration<WorkspaceMember>
{
    public void Configure(EntityTypeBuilder<WorkspaceMember> builder)
    {
        // Named explicitly: members have no DbSet (they are reached only through Workspace), so
        // EF would otherwise name the table after the CLR type — the singular workspace_member.
        builder.ToTable("workspace_members", table => table.HasCheckConstraint(
            "ck_workspace_members_role",
            "role IN ('Owner', 'Member')"));

        builder.HasKey(member => member.Id);

        // Never generated by the database. This also matters for how EF treats a member added
        // to an already-loaded workspace: a key it does not generate itself, discovered through
        // the navigation, is an INSERT — not an UPDATE of a row that does not exist.
        builder.Property(member => member.Id)
            .ValueGeneratedNever();

        // Text, not an int: see WorkspaceRole. Keep the CHECK above in step with the enum.
        builder.Property(member => member.Role)
            .HasConversion<string>()
            .IsRequired();

        builder.Property(member => member.JoinedAt).IsRequired();

        // The second line of defence behind Workspace.AddMember — it also covers two requests
        // adding the same user concurrently, which no in-memory check can see.
        builder.HasIndex(member => new { member.WorkspaceId, member.UserId })
            .IsUnique();

        // Not optional (DEVHUB-023): every authorization query in the system starts from the
        // user — "which workspaces is this user in?" — and the unique index above leads with
        // workspace_id, so it cannot serve that lookup.
        builder.HasIndex(member => member.UserId);

        // Deleting a user removes their memberships; the last-owner rule for that case belongs
        // to account deletion, which is post-MVP.
        builder.HasOne<User>()
            .WithMany()
            .HasForeignKey(member => member.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
